# Generated by Django 2.0 on 2017-12-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=5, verbose_name='单位')),
                ('qry', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='金额')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=210, verbose_name='单价')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='成本')),
                ('code', models.CharField(max_length=13, verbose_name='条码')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Res_Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, verbose_name='名称')),
                ('addres', models.CharField(max_length=13, verbose_name='地址')),
                ('phone', models.CharField(max_length=13, verbose_name='电话')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13, verbose_name='单号')),
                ('date', models.DateField(max_length=13, verbose_name='日期')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('partner_id', models.ForeignKey(on_delete='业务伙伴', to='sale.Res_Partner')),
            ],
        ),
        migrations.AddField(
            model_name='order_line',
            name='product_id',
            field=models.ForeignKey(on_delete='产品', to='sale.Product_Product'),
        ),
        migrations.AddField(
            model_name='order_line',
            name='sale_id',
            field=models.ForeignKey(on_delete='主表', to='sale.Sale_Order'),
        ),
    ]
